CREATE TABLE SHIP (
  ID                INT NOT NULL AUTO_INCREMENT,
  CODE              VARCHAR(2) NOT NULL,
  NAME              VARCHAR(25),
  INSERT_DATE       DATETIME,
  LAST_UPDATE_DATE  DATETIME,

  PRIMARY KEY (ID)
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;
