CREATE TABLE PORT(
  ID                INT NOT NULL AUTO_INCREMENT,
  CODE              VARCHAR(10) NOT NULL,
  NAME              VARCHAR(100),
  DATE              DATE,
  ARRIVE_TIME       TIME,
  BOARDING_TIME     TIME,
  DEPART_TIME       TIME,
  ITINERARY_ID      INT,
  INSERT_DATE       DATETIME,
  LAST_UPDATE_DATE  DATETIME,
  PRIMARY KEY (ID),
  FOREIGN KEY (ITINERARY_ID) REFERENCES ITINERARY(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;