CREATE TABLE CATEGORY_CABIN_DECK(
  ID                    INT  NOT NULL AUTO_INCREMENT,
  CATEGORY_ID           INT NOT NULL,
  CABIN_DECK_ID         INT NOT NULL,
  INSERT_DATE           DATETIME,
  LAST_UPDATE_DATE      DATETIME,

  PRIMARY KEY(ID),
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE,
  FOREIGN KEY(CABIN_DECK_ID) REFERENCES CABIN_DECK(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;