CREATE TABLE PORT(
  ID                INT NOT NULL AUTO_INCREMENT,
  PRODUCT_ID        INT NOT NULL,
  CODE              VARCHAR(10) NOT NULL,
  NAME              VARCHAR(100),
  DATE              DATE,
  ARRIVE_TIME       TIME,
  BOARDING_TIME     TIME,
  DEPART_TIME       TIME,
  INSERT_DATE       DATETIME,
  LAST_UPDATE_DATE  DATETIME,
  PRIMARY KEY (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;