CREATE TABLE CATEGORY (
  ID                    INT NOT NULL AUTO_INCREMENT,
  CODE                  VARCHAR(6) NOT NULL,
  NAME                  VARCHAR(100) NOT NULL,
  CABIN_STATUS          VARCHAR(2),
  CABIN_TYPE            VARCHAR(10),
  CABIN_SUB_TYPE        VARCHAR(2),
  CABIN_SUB_TYPE_DESC   VARCHAR(20),
  PRODUCT_ID            INT NOT NULL,
  CABIN_LOCATION_ID     INT NOT NULL,
  CABIN_DECK_ID         INT NOT NULL,
  INSERT_DATE           DATETIME,
  LAST_UPDATE_DATE      DATETIME,

  PRIMARY KEY(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
  FOREIGN KEY(CABIN_LOCATION_ID) REFERENCES CABIN_LOCATION(ID) ON DELETE CASCADE,
  FOREIGN KEY(CABIN_DECK_ID) REFERENCES CABIN_DECK(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;