CREATE TABLE GUEST_TYPE(
  ID                    INT NOT NULL AUTO_INCREMENT,
  STATUS_CODE           VARCHAR(2),
  DESCRIPTION           VARCHAR(30),
  CODE                  VARCHAR(6),
  CATEGORY_ID           INT NOT NULL,
  INSERT_DATE           DATETIME,
  LAST_UPDATE_DATE      DATETIME,

  PRIMARY KEY(ID),
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;