CREATE TABLE TRANSPORTATION(
  ID                    INT NOT NULL AUTO_INCREMENT,
  STATUS_CODE           VARCHAR(2) NOT NULL,
  DESCRIPTION           VARCHAR(30),
  RATE_PORT_CHARGE      CHAR(1),
  RATE_TYPE             CHAR(1),
  RATE_CODE             VARCHAR(3),
  RATE_NAME             VARCHAR(30),
  AMOUNT                DECIMAL(7,2),
  TYPE                  CHAR(1),
  TAX_FREE_AMOUNT       DECIMAL(7,2),
  GUEST_MIN             INT,
  GUEST_MAX             INT,
  GUEST_TYPE_ID         INT NOT NULL,
  INSERT_DATE           DATETIME,
  LAST_UPDATE_DATE      DATETIME,

  PRIMARY KEY(ID),
  FOREIGN KEY(GUEST_TYPE_ID) REFERENCES GUEST_TYPE(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;